//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.5448
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyNameSpace.Screens
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public interface InformationService
    {
        
        MyNameSpace.Screens.UserInformation GetUserInfo(int userId);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("NetCFSvcUtil", "3.5.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/MyNameSpace")]
    public partial class UserInformation
    {
        
        private System.Nullable<int> ageField;
        
        private bool ageFieldSpecified;
        
        private string userNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public System.Nullable<int> Age
        {
            get
            {
                return this.ageField;
            }
            set
            {
                this.ageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool AgeSpecified
        {
            get
            {
                return this.ageFieldSpecified;
            }
            set
            {
                this.ageFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public string UserName
        {
            get
            {
                return this.userNameField;
            }
            set
            {
                this.userNameField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Xml.Serialization.XmlRootAttribute(ElementName="GetUserInfo", Namespace="http://schemas.a-t-g.com/2010/08/web/services")]
    public partial class GetUserInfoRequest
    {
        
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://schemas.a-t-g.com/2010/08/web/services", Order=0)]
        public int userId;
        
        public GetUserInfoRequest()
        {
        }
        
        public GetUserInfoRequest(int userId)
        {
            this.userId = userId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Xml.Serialization.XmlRootAttribute(ElementName="GetUserInfoResponse", Namespace="http://schemas.a-t-g.com/2010/08/web/services")]
    public partial class GetUserInfoResponse
    {
        
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Namespace="http://schemas.a-t-g.com/2010/08/web/services", Order=0)]
        public MyNameSpace.Screens.UserInformation GetUserInfoResult;
        
        public GetUserInfoResponse()
        {
        }
        
        public GetUserInfoResponse(MyNameSpace.Screens.UserInformation GetUserInfoResult)
        {
            this.GetUserInfoResult = GetUserInfoResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class InformationServiceClient : Microsoft.Tools.ServiceModel.CFClientBase<MyNameSpace.Screens.InformationService>, MyNameSpace.Screens.InformationService
    {
        
        public static System.ServiceModel.EndpointAddress EndpointAddress = new System.ServiceModel.EndpointAddress("http://localhost:1000/Services/InformationScreenService.svc");
        
        public InformationServiceClient() : 
                this(CreateDefaultBinding(), EndpointAddress)
        {
        }
        
        public InformationServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
            addProtectionRequirements(binding);
        }
        
        private MyNameSpace.Screens.GetUserInfoResponse GetUserInfo(MyNameSpace.Screens.GetUserInfoRequest request)
        {
            CFInvokeInfo info = new CFInvokeInfo();
            info.Action = "http://schemas.a-t-g.com/2010/08/web/services/InformationService/GetUserInfo";
            info.RequestIsWrapped = true;
            info.ReplyAction = "http://schemas.a-t-g.com/2010/08/web/services/InformationService/GetUserInfoRespo" +
                "nse";
            info.ResponseIsWrapped = true;
            MyNameSpace.Screens.GetUserInfoResponse retVal = base.Invoke<MyNameSpace.Screens.GetUserInfoRequest, MyNameSpace.Screens.GetUserInfoResponse>(info, request);
            return retVal;
        }
        
        public MyNameSpace.Screens.UserInformation GetUserInfo(int userId)
        {
            GetUserInfoRequest request = new GetUserInfoRequest(userId);
            GetUserInfoResponse response = this.GetUserInfo(request);
            return response.GetUserInfoResult;
        }
        
        public static System.ServiceModel.Channels.Binding CreateDefaultBinding()
        {
            System.ServiceModel.Channels.CustomBinding binding = new System.ServiceModel.Channels.CustomBinding();
            binding.Elements.Add(new System.ServiceModel.Channels.TextMessageEncodingBindingElement(System.ServiceModel.Channels.MessageVersion.Soap11, System.Text.Encoding.UTF8));
            binding.Elements.Add(new System.ServiceModel.Channels.HttpTransportBindingElement());
            return binding;
        }
        
        private void addProtectionRequirements(System.ServiceModel.Channels.Binding binding)
        {
            if ((IsSecureMessageBinding(binding) == false))
            {
                return;
            }
            System.ServiceModel.Security.ChannelProtectionRequirements cpr = new System.ServiceModel.Security.ChannelProtectionRequirements();
            ApplyProtection("http://schemas.a-t-g.com/2010/08/web/services/InformationService/GetUserInfo", cpr.IncomingSignatureParts, true);
            ApplyProtection("http://schemas.a-t-g.com/2010/08/web/services/InformationService/GetUserInfo", cpr.IncomingEncryptionParts, true);
            if ((binding.MessageVersion.Addressing == System.ServiceModel.Channels.AddressingVersion.None))
            {
                ApplyProtection("*", cpr.OutgoingSignatureParts, true);
                ApplyProtection("*", cpr.OutgoingEncryptionParts, true);
            }
            else
            {
                ApplyProtection("http://schemas.a-t-g.com/2010/08/web/services/InformationService/GetUserInfoRespo" +
                        "nse", cpr.OutgoingSignatureParts, true);
                ApplyProtection("http://schemas.a-t-g.com/2010/08/web/services/InformationService/GetUserInfoRespo" +
                        "nse", cpr.OutgoingEncryptionParts, true);
            }
            this.Parameters.Add(cpr);
        }
    }
}
